FROM openjdk:8-jdk-alpine
LABEL maintainer="javajvm007@gmail.com"
EXPOSE 8080
ADD /target/springdockermysqldemo.jar springdockermysqldemo.jar
ENTRYPOINT ["java", "-jar", "springdockermysqldemo.jar"] 